services:
  postgres:
    image: postgres:17
    container_name: labaik-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: labaik
    ports:
      - "5433:5432"
    volumes:
      - labaik-postgres-data:/var/lib/postgresql/data

volumes:
  labaik-postgres-data: