using Labaik.Domain.Common;
using Labaik.Domain.Common.Results;
using Labaik.Domain.Groups.Enums;
using Labaik.Domain.Groups.Events;

namespace Labaik.Domain.Groups;

public sealed class Group : AggregateRoot
{
    public string Name { get; private set; } = string.Empty;
    public string JoinCode { get; private set; } = string.Empty;
    public Guid LeaderId { get; private set; }

    private readonly List<GroupMember> _members = [];
    public IReadOnlyList<GroupMember> Members => _members.AsReadOnly();

    public int MemberCount => _members.Count;

    private Group() { } // EF

    private Group(string name, string joinCode, Guid leaderId, DateTimeOffset createdAtUtc)
    {
        Name = name;
        JoinCode = joinCode;
        LeaderId = leaderId;

        // The leader is the first member.
        _members.Add(new GroupMember(leaderId, GroupMemberRole.Leader, createdAtUtc));
        Raise(new GroupCreated(Id, leaderId));
    }

    // Factory: joinCode is supplied by the app layer (generated by an infrastructure service).
    public static Result<Group> Create(string name, string joinCode, Guid leaderId, DateTimeOffset createdAtUtc)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            return GroupErrors.NameRequired;
        }

        if (string.IsNullOrWhiteSpace(joinCode))
        {
            return GroupErrors.JoinCodeRequired;
        }

        if (leaderId == Guid.Empty)
        {
            return GroupErrors.LeaderRequired;
        }

        return new Group(name.Trim(), joinCode.Trim().ToUpperInvariant(), leaderId, createdAtUtc);
    }

    public Result Join(Guid userId, DateTimeOffset joinedAtUtc)
    {
        if (_members.Any(m => m.UserId == userId))
        {
            return Result.Failure(GroupErrors.AlreadyMember);
        }

        _members.Add(new GroupMember(userId, GroupMemberRole.Member, joinedAtUtc));
        Raise(new MemberJoinedGroup(Id, userId));
        return Result.Success();
    }
}